#!/usr/bin/env python3
"""
Asset Finder - DMI JSON State Scanner

Scans Resources/Textures for DMI-to-JSON files and extracts state names.

Usage:
    python asset_finder.py              # Summary mode - list all files and state counts
    python asset_finder.py floor        # Search mode - find states containing "floor"
    python asset_finder.py --generate   # Generate C# SpriteStates enum
    python asset_finder.py fire --path ../Resources/Textures/OldSprites/effects
"""

import json
import os
import sys
import argparse
import re
from pathlib import Path
from typing import Dict, List, Tuple, Set
from collections import defaultdict


def find_json_files(root_dir: Path) -> List[Path]:
    """Recursively find all .json files in directory."""
    return list(root_dir.rglob("*.json"))


def parse_dmi_json(file_path: Path) -> Tuple[List[str], str | None, Dict | None]:
    """
    Parse a DMI JSON file and extract state names.
    
    Returns:
        Tuple of (state_names, image_file, meta_info)
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        states = []
        meta = data.get('meta', {})
        image_file = meta.get('image')
        
        # Extract state keys from "states" object
        if 'states' in data and isinstance(data['states'], dict):
            states = list(data['states'].keys())
        
        return states, image_file, meta
        
    except json.JSONDecodeError as e:
        return [], None, {'error': f'Invalid JSON: {e}'}
    except Exception as e:
        return [], None, {'error': str(e)}


def scan_all_states(root_dir: Path) -> Dict[str, List[Tuple[str, Path]]]:
    """
    Scan all JSON files and collect states.
    
    Returns:
        Dict mapping state_name -> [(image_file, json_path), ...]
    """
    states_map = defaultdict(list)
    
    for json_file in find_json_files(root_dir):
        states, image_file, meta = parse_dmi_json(json_file)
        
        for state in states:
            states_map[state].append((image_file or 'unknown', json_file))
    
    return states_map


def search_states(root_dir: Path, query: str, case_sensitive: bool = False) -> List[Tuple[str, str, Path]]:
    """
    Search for states containing query string.
    
    Returns:
        List of (state_name, image_file, json_path)
    """
    results = []
    query_lower = query if case_sensitive else query.lower()
    
    for json_file in find_json_files(root_dir):
        states, image_file, meta = parse_dmi_json(json_file)
        
        for state in states:
            state_check = state if case_sensitive else state.lower()
            if query_lower in state_check:
                results.append((state, image_file or 'unknown', json_file))
    
    return results


def summarize_directory(root_dir: Path) -> Tuple[int, int, int, Dict[str, int]]:
    """
    Generate summary statistics.
    
    Returns:
        Tuple of (total_files, valid_files, total_states, states_per_file)
    """
    json_files = find_json_files(root_dir)
    total_files = len(json_files)
    valid_files = 0
    total_states = 0
    states_per_file = {}
    errors = []
    
    for json_file in json_files:
        states, image_file, meta = parse_dmi_json(json_file)
        
        if 'error' in (meta or {}):
            errors.append((json_file, meta['error']))
        else:
            valid_files += 1
            state_count = len(states)
            total_states += state_count
            states_per_file[str(json_file.relative_to(root_dir))] = state_count
    
    return total_files, valid_files, total_states, states_per_file, errors


def generate_csharp_enum(root_dir: Path, output_path: Path, namespace: str = "SpaceStation.Client.Graphics") -> int:
    """
    Generate C# enum with all sprite state names.
    
    Returns:
        Number of states generated.
    """
    states_map = scan_all_states(root_dir)
    
    # Convert state names to valid C# identifiers
    def to_identifier(name: str) -> str:
        # Replace invalid characters
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        # Ensure doesn't start with digit
        if clean and clean[0].isdigit():
            clean = '_' + clean
        # Convert to PascalCase
        parts = clean.split('_')
        return ''.join(p.capitalize() for p in parts if p)
    
    # Group by prefix for organization
    unique_states = sorted(set(states_map.keys()))
    
    # Build enum content
    lines = [
        "// Auto-generated by tools/asset_finder.py",
        "// Do not edit manually - regenerate with: python tools/asset_finder.py --generate",
        "",
        f"namespace {namespace};",
        "",
        "/// <summary>",
        "/// All available sprite state names from DMI JSON files.",
        "/// </summary>",
        "public static class SpriteStates",
        "{",
    ]
    
    for state in unique_states:
        identifier = to_identifier(state)
        if identifier:
            # Escape quotes in state name for string literal
            escaped_state = state.replace('"', '\\"')
            lines.append(f'    public const string {identifier} = "{escaped_state}";')
    
    lines.append("}")
    lines.append("")
    
    # Write file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    return len(unique_states)


def print_color(text: str, color: str) -> None:
    """Print colored text (if terminal supports it)."""
    colors = {
        'green': '\033[92m',
        'yellow': '\033[93m',
        'red': '\033[91m',
        'blue': '\033[94m',
        'cyan': '\033[96m',
        'reset': '\033[0m',
        'bold': '\033[1m',
    }
    
    if sys.stdout.isatty():
        print(f"{colors.get(color, '')}{text}{colors['reset']}")
    else:
        print(text)


def main():
    parser = argparse.ArgumentParser(
        description="Scan DMI JSON files for sprite state names",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python asset_finder.py                    # Show summary
  python asset_finder.py floor              # Search for "floor"
  python asset_finder.py human --exact      # Exact match only
  python asset_finder.py --generate         # Generate C# enum
  python asset_finder.py --list-files       # List all JSON files
        """
    )
    
    parser.add_argument('query', nargs='?', help='Search query for state names')
    parser.add_argument('--path', '-p', default='../Resources/Textures',
                        help='Root directory to scan (default: ../Resources/Textures)')
    parser.add_argument('--generate', '-g', action='store_true',
                        help='Generate C# SpriteStates.cs enum')
    parser.add_argument('--output', '-o', default='../src/SpaceStation.Client/Graphics/SpriteStates.cs',
                        help='Output path for generated C# file')
    parser.add_argument('--exact', '-e', action='store_true',
                        help='Exact match only (not substring)')
    parser.add_argument('--case-sensitive', '-c', action='store_true',
                        help='Case-sensitive search')
    parser.add_argument('--list-files', '-l', action='store_true',
                        help='List all JSON files with state counts')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Show detailed output')
    
    args = parser.parse_args()
    
    # Resolve paths relative to script location
    script_dir = Path(__file__).parent
    root_dir = (script_dir / args.path).resolve()
    
    if not root_dir.exists():
        print_color(f"Error: Directory not found: {root_dir}", 'red')
        sys.exit(1)
    
    print_color(f"📁 Scanning: {root_dir}", 'cyan')
    print()
    
    # Mode: Generate C# enum
    if args.generate:
        output_path = (script_dir / args.output).resolve()
        print_color(f"🔧 Generating C# enum...", 'yellow')
        
        count = generate_csharp_enum(root_dir, output_path)
        
        print_color(f"✅ Generated {count} constants in:", 'green')
        print(f"   {output_path}")
        return
    
    # Mode: List files
    if args.list_files:
        total, valid, states, per_file, errors = summarize_directory(root_dir)
        
        print_color(f"📄 JSON Files ({valid}/{total} valid):", 'bold')
        print()
        
        # Sort by state count descending
        sorted_files = sorted(per_file.items(), key=lambda x: -x[1])
        
        for file_path, count in sorted_files:
            print(f"  {count:5d} states  │  {file_path}")
        
        if errors:
            print()
            print_color(f"⚠️  {len(errors)} files with errors:", 'yellow')
            for path, error in errors[:10]:
                print(f"   {path}: {error}")
        
        return
    
    # Mode: Search
    if args.query:
        results = search_states(root_dir, args.query, args.case_sensitive)
        
        if args.exact:
            query_check = args.query if args.case_sensitive else args.query.lower()
            results = [(s, i, p) for s, i, p in results 
                       if (s if args.case_sensitive else s.lower()) == query_check]
        
        if results:
            print_color(f"🔍 Found {len(results)} states matching '{args.query}':", 'green')
            print()
            
            # Group by file
            by_file = defaultdict(list)
            for state, image, json_path in results:
                rel_path = json_path.relative_to(root_dir)
                by_file[str(rel_path)].append((state, image))
            
            for file_path, states in sorted(by_file.items()):
                print_color(f"  📄 {file_path}", 'blue')
                for state, image in sorted(states, key=lambda x: x[0]):
                    print(f"     └─ '{state}' (image: {image})")
                print()
        else:
            print_color(f"❌ No states found matching '{args.query}'", 'red')
        
        return
    
    # Mode: Summary (default)
    total, valid, states, per_file, errors = summarize_directory(root_dir)
    
    print_color("═" * 50, 'cyan')
    print_color("        DMI JSON Asset Summary", 'bold')
    print_color("═" * 50, 'cyan')
    print()
    
    print(f"  📁 Total JSON files:    {total}")
    print(f"  ✅ Valid DMI files:     {valid}")
    print(f"  ❌ Files with errors:   {len(errors)}")
    print(f"  🎨 Total sprite states: {states}")
    print()
    
    if per_file:
        # Top 10 files by state count
        top_files = sorted(per_file.items(), key=lambda x: -x[1])[:10]
        
        print_color("📊 Top 10 files by state count:", 'yellow')
        for i, (file_path, count) in enumerate(top_files, 1):
            print(f"  {i:2d}. {count:5d} states  │  {file_path}")
    
    print()
    print_color("💡 Usage tips:", 'cyan')
    print("  • Search:    python asset_finder.py floor")
    print("  • Generate:  python asset_finder.py --generate")
    print("  • List all:  python asset_finder.py --list-files")


if __name__ == '__main__':
    main()
